# https://wiki.archlinux.org/index.php/Network_configuration
network:
  interfaces:
    - { name: 'enp0s3', address: 'dhcp' }

# https://wiki.archlinux.org/index.php/beginners%27_guide#Prepare_the_storage_devices
storage:

  # disk to use
  name: /dev/sda
  # physical partition to write volumes, a new one will be created at the end of the last partition if not informed
  #partition: /dev/sda1
  # partition table for device /dev/sda. Use lsblk to know the disks available.
  volumes:
    - { size: '4g', type: 'swap' }
    - { size: '512m', type: 'ext4', mount: '/boot' }
    - { size: '100%FREE', type: 'ext4', mount: '/' }

# https://wiki.archlinux.org/index.php/beginners%27_guide#Locale
locale:
  # languages to be enabled. Note that the first one will be exported to LANG: https://wiki.archlinux.org/index.php/beginners%27_guide#Locale
  languages:
    - 'pt_BR.UTF-8 UTF-8'
    - 'en_US.UTF-8 UTF-8'
  keymap: br-abnt2
  font: Lat2-Terminus16
  timezone: Brazil/East

#  User section, instructions, please note the following:
#  - Most params are managed by ansible users module: http://docs.ansible.com/user_module.html
#  - The 'sudo' special param may have the following values: no (default), yes (allows sudo with password) and passwordless (allows sudo without informing password)
#  - The 'root' user allows a special param named 'ssh', which enables (or disables) ssh login. Default is 'no'.
users:
  - { name: 'root', ssh: 'no', password: '$6$rounds=100000$nE29QdsJf.NuSuXJ$3yCvDNN6kBP42A50V1DjfNOI0Syw71jV3fbCkzYPjWZu6f.zsgQMrfiSjzm1TTzxOlufCUX.faut.uFJaZckv/' }
  - { name: 'andre', groups: 'adm,users', sudo: 'passwordless', password: '$6$rounds=100000$4qfmUuShRlw2NzbH$Mk1eI65Z2oKoj66QKohNnl05iByh3sQ4pUlEXGKE3xrYKMyR5xZ.b.7EY1MrKkqTWX7dE91zAUHyi4Eu1DBwi0' }

# https://wiki.archlinux.org/index.php/Samba#Client_configuration
# samba:
#   mount:
#     - { path: '/mnt/share', src: '//myserver/sharename', username: 'username', password: 'password' }

packages:
  # https://www.archlinux.org/packages/
  official:
    - vim
    - wget
    - curl
    - lightdm
    - openbox
    - xf86-video-ati
    - fuse-exfat
    - chromium
services:
    - lightdm
