# https://wiki.archlinux.org/index.php/Network_configuration
network:
  hostname: 'archlinux-vagrant'
  interfaces:
    - { name: 'enp0s3', address: 'dhcp' }
    #- { name: 'enp0s3', address: '10.0.0.2', gateway: '10.0.0.1', dns: '10.0.0.1, 10.0.0.2', domain: 'mydomain.com' }

# https://wiki.archlinux.org/index.php/beginners%27_guide#Prepare_the_storage_devices
storage:
  # partition table for device /dev/sda. Use lsblk to know the disks available.
  /dev/sda:
    boot: grub
    # storage use policy. Accepts:
    # overwrite: Erases the disk and uses all space to create the volumes
    # 1-100%: Creates the volumes using desired storage free space. Nothing that is already created is erased.
    use: overwrite
    volumes:
      - { size: '512m', type: 'swap' }
      - { size: '512m', type: 'ext4', mount: '/boot' }
      - { size: '100%FREE', type: 'ext4', mount: '/' }

# https://wiki.archlinux.org/index.php/beginners%27_guide#Locale
locale:
  # languages to be enabled. Note that the first one will be exported to LANG: https://wiki.archlinux.org/index.php/beginners%27_guide#Locale
  languages:
    - 'pt_BR.UTF-8 UTF-8'
    - 'en_US.UTF-8 UTF-8'
  keymap: br-abnt2
  font: Lat2-Terminus16
  timezone: Brazil/East

#  User section, instructions, please note the following:
#  - Most params are managed by ansible users module: http://docs.ansible.com/user_module.html
#  - The 'sudo' special param may have the following values: no (default), yes (allows sudo with password) and passwordless (allows sudo without informing password)
#  - The 'root' user allows a special param named 'ssh', which enables (or disables) ssh login. Default is 'no'.
users:
  - { name: 'root', ssh: 'no', password: '$6$rounds=100000$nE29QdsJf.NuSuXJ$3yCvDNN6kBP42A50V1DjfNOI0Syw71jV3fbCkzYPjWZu6f.zsgQMrfiSjzm1TTzxOlufCUX.faut.uFJaZckv/' }
  - { name: 'andre', groups: 'adm,users', sudo: 'passwordless', password: '$6$rounds=100000$nE29QdsJf.NuSuXJ$3yCvDNN6kBP42A50V1DjfNOI0Syw71jV3fbCkzYPjWZu6f.zsgQMrfiSjzm1TTzxOlufCUX.faut.uFJaZckv/' }

# https://wiki.archlinux.org/index.php/Samba#Client_configuration
samba:
  mount:
    - { path: '/mnt/share', src: '//myserver/sharename', username: 'username', password: 'password' }

packages:
  # https://www.archlinux.org/packages/
  official:
    - vim
  aur:
    - rar
