# file containing misc variables used in an archlinux installation process

grep_exec: /usr/bin/grep
vgcreate_exec: /usr/bin/vgcreate -y
parted_exec: /usr/bin/parted -s
mkswap_exec: /usr/bin/mkswap
locale_gen_exec: /usr/bin/locale-gen
yaourt_exec: /usr/bin/yaourt -S --noconfirm --needed
makepkg_exec: /usr/bin/makepkg
eclipse_exec: /usr/bin/eclipse
