---
- name: "Enables systemd-resolved service"
  service: name=systemd-resolved.service enabled=yes state=started
  when: network.dns is not defined

- name: "Creates symbolic link from /run/systemd/resolve/resolv.conf to /etc/resolv.conf"
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    force: yes
    state: link
  when: network.dns is not defined
