---
- name: "Enables systemd.networkd service"
  service: name=systemd-networkd.service enabled=yes

- name: "Enables sshd.service"
  service: name=sshd.service enabled=yes

- name: "Copies template file to temp dir"
  copy: src=resources/systemd-networkd.j2 dest=/tmp/systemd-networkd.j2

- name: "Creates network configuration for each device"
  template:
    src: /tmp/systemd-networkd.j2
    dest: "/etc/systemd/network/{{ item.name }}.network"
  with_items: network.interfaces
