---
  - name: "updates pacman cache"
    pacman:  update_cache=yes

  - name: "install packages from official repository"
    pacman: name={{item}}
    with_items: packages.official
    when: packages.official is defined

  - name: "Prepares yaourt to fetch from aur repository"
    include: yaourt.yml
    when: packages.aur is defined

  - name: "install packages from aur repository"
    command: "{{ yaourt_exec }} {{item}}"
    with_items: packages.aur
    when: packages.aur is defined

  - stat: "{{ eclipse_exec }}"
    register: "eclipse_exec_status"

  - name: "install packages for eclipse if necessary"
    command: "{{ eclipse_exec }} -application org.eclipse.equinox.p2.director -repository {{item.repository}} -installIU {{item.feature}}"
    with_items: packages.eclipse
    when: eclipse_exec_status.exists and packages.eclipse is defined
