---
  - name: "updates pacman cache"
    pacman:  update_cache=yes

  - name: "updates pacman key cache"
    command:  pacman-key --refresh

  - name: "install git package"
    pacman: name=git

  - name: "install packages from official repository"
    pacman: name={{item}}
    with_items: packages.official
    when: packages.official is defined

  - name: "install packages from aur repository"
    command: "{{ yaourt_exec }} {{item}}"
    with_items: packages.aur
    when: packages.aur is defined
    become: yes
    become_user: andre

  - name: "Enables configured services"
    service: "name={{item}}.service enabled=yes state=started"
    with_items: services
    when: services is defined
