---
- name: "Installs base system using pacstrap"
  command: /usr/bin/pacstrap /mnt base base-devel ansible

- name: "Populates base system fstab with configured storage devices"
  shell: /usr/bin/genfstab -U -p /mnt >> /mnt/etc/fstab
