---
- name: "Creates partition table on storage"
  command: "{{ parted_exec }} {{ storage.name }} mklabel msdos"

- name: "Creates physical partition with 513M offset and enables LVM, filling all the remaining space."
  shell: "{{ parted_exec }} {{ storage.name }} mkpart primary ext4 1M 100% && {{ parted_exec }} {{ storage.name }} set 1 lvm on"

- name: "Creates a volume group for the physical partition."
  lvg:
    pvs: "{{ storage.name }}1"
    vg: "{{ vg }}"
    force: yes

- name: "Creates logical partitions for each volume group for root partition"
  lvol:
    vg: "{{ vg }}"
    lv: "vl_{{ item.0 }}"
    size: "{{ item.1.size }}"
  with_indexed_items: storage.volumes

- name: "Format data values"
  filesystem:
    fstype: "{{ item.1.type }}"
    dev: "/dev/{{ vg }}/vl_{{ item.0 }}"
  when: item.1.type != "swap"
  with_indexed_items: storage.volumes

- name: "Setup swap partition"
  shell: "{{ mkswap_exec }} /dev/{{ vg }}/vl_{{ item.0 }} && /usr/bin/swapon /dev/{{ vg }}/vl_{{ item.0 }}"
  when: item.1.type == "swap"
  with_indexed_items: storage.volumes

- name: "Mount volumes"
  mount:
    name: "/mnt{{ item.1.mount }}"
    src: "/dev/{{ vg }}/vl_{{ item.0 }}"
    fstype: "{{ item.1.type }}"
    opts: defaults
    state: mounted
  when: item.1.type != "swap"
  with_indexed_items: storage.volumes
